name: Actions example with OCI runner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted
    name: Testing

    steps:
      - name: OCIR token setup
        run: |
          echo "Hello"
