name: Actions example with OCI runner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted
    name: Testing

    steps:
      - name: OCIR token setup
        run: |
          oci raw-request --region eu-frankfurt-1 --http-method GET --target-uri 'https://fra.ocir.io/20180419/docker/token' --auth=instance_principal  | jq -r .data.token | docker login -u BEARER_TOKEN --password-stdin fra.ocir.io
          docker pull mikarinneoracle/hello-world-java-graalvm:latest
